name: 🕊️ Unblock channel
description: Request to remove a channel from the blocklist
title: 'Unblock: '
labels: ['blocklist:remove']

body:
  - type: input
    attributes:
      label: Channel ID (required)
      description: The ID of the channel that should be removed
      placeholder: 'AnhuiTV.cn'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Reason (required)
      description: Select the reason for removal from the list below
      options:
        - 'Invalid channel id'
        - 'Other'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: 'Any additional information'
